### ISSUE TITLE
Number keypad inoperative on alphanumeric search

### ISSUE THREAD

**Issue by andrewgbuck** [AppGeo/GPV#59] opened 2015-09-30 20:35 UTC
SEARCH:
> It would be nice to be able to use the number pad to enter in numbers rather than needing to type with the numbers above the letters.
-----
On my phone

SEARCH:
> text seems to be fine, but numbers don’t enter into the typed search boxes unless I type my number (tree ID) and then click the autocorrect for that number at the top of the keypad
-----
From Stephanie Weyer at KZLA/ENC

**Comment by dbreeding** [comment] 2015-10-07 15:16
Duplicate of #40

**Closed** 2015-10-16 17:04 UTC
