### ISSUE TITLE
Add a configuration item to make the default tool Identify

### ISSUE THREAD

**Issue by seansweeney** [AppGeo/GPV#89] opened 2016-02-16 13:22 UTC
I apologize if this is already there, but I can't find it if so.

I know I can do it through the URL, but I'd like to set Identify to be the default tool whether or not I control the URL, including for the default app.

Pan seems almost uncecessary now since Identify can also pan, and the Identify/Pan combo is what our users expect from other web maps.

**Comment by pgirard** [comment] 2016-02-16 14:12
Duplicate of #74.  Planned for the next release.

**Comment by pgirard** [comment] 2016-02-16 14:15
No problem, I found it.  We're planning to add this at the next version.

On Tue, Feb 16, 2016 at 8:22 AM, Sean Sweeney <notifications@github.com>
wrote:

> I apologize if this is already there, but I can't find it if so.
>
> I know I can do it through the URL, but I'd like to set Identify to be the
> default tool whether or not I control the URL, including for the default
> app.
>
> Pan seems almost uncecessary now since Identify can also pan, and the
> Identify/Pan combo is what our users expect from other web maps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AppGeo/GPV/issues/89>.
>



-- 
*Peter Girard*
*Vice President*
617-447-2424 Direct | 617-447-2400 Main
Applied Geographics, Inc.
24 School Street, Suite 500
Boston, MA 02108
www.AppGeo.com

-- 
This e-mail message and any attachments may contain confidential or legally 
privileged information. If you are not an intended recipient or otherwise 
authorized to receive this message, you should not use, copy, distribute, 
disclose or take any action based on the information contained in this 
e-mail or any attachments. If you have received this message and material 
in error, please advise the sender immediately by reply e-mail and delete 
this message. Thank you on behalf of Applied Geographics, Inc. (AppGeo).

**Comment by seansweeney** [comment] 2016-02-16 14:23
Doh - by me no less.  Thanks Peter!

**Comment by pgirard** [comment] 2016-08-09 20:49
Added in Beta 1.

**Closed by pgirard** 2016-08-09 20:49 UTC
Labels: duplicate
