### ISSUE TITLE
Selection tool not working 

### ISSUE THREAD

**Issue by AmherstGIS** [AppGeo/GPV#68] opened 2015-10-29 13:34 UTC
Not working since installing the newest version of AppGeo.Clients.dll (10/27/2015 build)

**Comment by dbreeding** [comment] 2015-11-11 19:03
Our testing of the most current development branch release gives the selection tool click and drag functionality for multi-feature selection, which was missing previously.  Some selection testing on this deployment *http://gis.amherstma.gov/gpv2015/viewer.aspx* in Chrome was successful.  Please reopen a new issue if your selection issue persists with some more details.  Thanks

**Comment by AmherstGIS** [comment] 2015-11-12 18:00
I'm sorry that I didn't provide more details. I tested this feature on Safari on a Mac, on which selection still does not work.

I've done some quick testing on a few other browsers:
Single-feature selection works on: MS IE/Edge on Windows, Firefox on Mac
Select with Shift or crtl works on: MS IE/Edge on Windows, Firefox on Mac
Multi-feature select by click/drag works on: MS IE/Edge on Windows

**Comment by pgirard** [comment] 2015-11-12 19:25
This is still an issue.  I cannot select features using my Android tablet in Chrome 46.

**Comment by pgirard** [comment] 2015-11-12 20:46
This wasn't caused by AppGeo.Clients.dll.  Rather it was a misunderstanding of how touch events work on a mobile device.  Now fixed.

**Closed by pgirard** 2015-11-12 20:46 UTC
