### ISSUE TITLE
Application.DefaultTool

### ISSUE THREAD

**Issue by andrewgbuck** [AppGeo/GPV#99] opened 2016-08-04 14:01 UTC
Can the URL parameter "tools" be exposed in the Application table to set a default tool?  For example, I have a configuration where I would like the tool to be initially set to "identify".

tool - The map tool to activate, one of: "pan", "identify", "select", "drawpoint", "drawline", "drawpolygon", "drawcircle", "drawtext", "drawcoordinates", "drawlength", "drawarea", "deletemarkup", "colorpicker" or "paintbucket". If not specified or if the specified tool is disabled, this defaults to "pan".

**Comment by pgirard** [comment] 2016-08-09 20:49
Duplicate of #74.  This was released as part of Beta 1.

**Closed by pgirard** 2016-08-09 20:49 UTC
