### ISSUE TITLE
Hide Function Panel

### ISSUE THREAD

**Issue by andrewgbuck** [AppGeo/GPV#112] opened 2017-04-27 12:54 UTC
Enable the ability to completely hide the function display.  Current functions hide the function display, but leave the space for the panel in place.

Being able to turn on the panel (i.e. the hamburger) if it is currently is also requested.

**Comment by ClaireBrill** [comment] 2017-09-20 19:22
+1 for closing the panel space as well. A user asked for the ability to load the map with both function and data panels closed.

**Comment by andrewgbuck** [comment] 2018-05-22 16:03
duplicte of #54

**Comment by pgirard** [comment] 2018-09-27 18:09
Duplicate of #116 which has been fixed.

**Closed by pgirard** 2018-09-27 18:09 UTC
Labels: enhancement
